/**
 * MedFactory — Product catalog (shared)
 */
window.MedFactoryCatalog = (function () {
  "use strict";

  const CATEGORIES = {
    all: { label: "All products", slug: "all" },
    "dummy-heads": { label: "Dummy Heads", slug: "dummy-heads" },
    "endo-teeth": { label: "Endo Teeth", slug: "endo-teeth" },
    "dental-casts": { label: "Dental Casts", slug: "dental-casts" },
    "dental-kits": { label: "Dental Kits", slug: "dental-kits" },
  };

  const PRODUCTS = [
    {
      id: "dh-001",
      sku: "MF-DH-001",
      name: "Dummy Head — Adult Standard",
      category: "dummy-heads",
      categoryLabel: "Simulation",
      price: 2450,
      compareAt: null,
      badge: "Bestseller",
      inStock: true,
      image: "images/dummy-head-open.jpg",
      gallery: [
        "images/dummy-head-open.jpg",
        "images/dummy-head-skull.jpg",
        "images/articulator.jpg",
        "images/typodont-1.jpg",
      ],
      desc: "Typodont-compatible adult head for operative & simulation lab",
      longDesc:
        "Train operative technique, access, and positioning on a realistic adult simulation head before clinic. Built for repeated semester use in Egyptian dental faculties — compatible with standard typodont mounting systems.",
      features: [
        "Typodont-compatible mounting plate",
        "Replaceable soft tissue mask",
        "Anatomically proportioned adult dentition",
        "Stable base for bench-top lab work",
        "Training-grade materials — not disposable novelty",
      ],
      specifications: {
        Type: "Adult simulation head",
        Compatibility: "Standard typodont systems",
        Material: "High-density resin + silicone mask",
        Weight: "Approx. 2.8 kg",
        Origin: "Training-grade import",
        Warranty: "6 months student use",
      },
      featured: 100,
      date: "2025-09-01",
    },
    {
      id: "dh-002",
      sku: "MF-DH-002",
      name: "Dummy Head — With Articulator",
      category: "dummy-heads",
      categoryLabel: "Simulation",
      price: 3200,
      compareAt: 3450,
      badge: "Popular",
      inStock: true,
      image: "images/articulator.jpg",
      gallery: [
        "images/articulator.jpg",
        "images/dummy-head-open.jpg",
        "images/typodont-1.jpg",
      ],
      desc: "Full articulation for prosthodontics and occlusion practice",
      longDesc:
        "Includes articulator for occlusion, prosthodontics, and crown-and-bridge modules. The same trusted build quality as our standard head with full jaw movement for realistic student training.",
      features: [
        "Integrated articulator with adjustable hinge",
        "Ideal for prostho & occlusion modules",
        "Replaceable soft tissue components",
        "Bench-stable mounting system",
        "Used in Year 3–4 simulation labs",
      ],
      specifications: {
        Type: "Adult head + articulator",
        Articulation: "Adjustable hinge, semi-adjustable",
        Compatibility: "Standard typodont plates",
        Weight: "Approx. 4.2 kg",
        Includes: "Head, articulator, mounting hardware",
        Warranty: "6 months student use",
      },
      featured: 90,
      date: "2025-08-15",
    },
    {
      id: "dh-003",
      sku: "MF-DH-003",
      name: "Replacement Soft Tissue Mask",
      category: "dummy-heads",
      categoryLabel: "Simulation",
      price: 450,
      compareAt: null,
      badge: null,
      inStock: true,
      image: "images/dummy-head-skull.jpg",
      gallery: [
        "images/dummy-head-skull.jpg",
        "images/dummy-head-open.jpg",
      ],
      desc: "Replaceable gingival mask for repeated student training",
      longDesc:
        "Refresh worn gingival tissue on your simulation head between semesters. Realistic soft-tissue feel for flap, suturing, and injection practice.",
      features: [
        "Fits MedFactory dummy head series",
        "Realistic gingival texture",
        "Easy snap-fit installation",
        "Sold per unit",
      ],
      specifications: {
        Type: "Replacement mask",
        Compatibility: "MedFactory DH series",
        Material: "Medical-grade silicone",
        Pack: "1 unit",
        Color: "Pink gingival",
      },
      featured: 40,
      date: "2025-06-20",
    },
    {
      id: "et-001",
      sku: "MF-ET-001",
      name: "Endo Teeth Set",
      category: "endo-teeth",
      categoryLabel: "Endodontics",
      price: 380,
      compareAt: null,
      badge: "Lab essential",
      inStock: true,
      image: "images/endo-teeth-red-roots.jpg",
      gallery: [
        "images/endo-teeth-red-roots.jpg",
        "images/endo-teeth-bulk.jpg",
        "images/typodont-1.jpg",
      ],
      desc: "8 teeth with realistic canal anatomy for access & shaping",
      longDesc:
        "Practice access cavities, canal negotiation, shaping, and obturation on models with anatomically realistic pulp chambers. The standard set for endodontics lab across Egyptian faculties.",
      features: [
        "Set of 8 practice teeth",
        "Realistic canal anatomy",
        "Compatible with standard mounting",
        "Ideal for Year 3 endo module",
        "Reorder-friendly semester pack",
      ],
      specifications: {
        Quantity: "8 teeth per set",
        Canal: "Standard + curved variants",
        Material: "Resin with pulp chamber",
        Mounting: "Standard typodont slot",
        Pack: "Retail box",
      },
      featured: 95,
      date: "2025-10-01",
    },
    {
      id: "et-002",
      sku: "MF-ET-002",
      name: "Endo Teeth — Bulk Pack (24)",
      category: "endo-teeth",
      categoryLabel: "Endodontics",
      price: 980,
      compareAt: 1140,
      badge: "Save 14%",
      inStock: true,
      image: "images/endo-teeth-bulk.jpg",
      gallery: [
        "images/endo-teeth-bulk.jpg",
        "images/endo-teeth-red-roots.jpg",
      ],
      desc: "Semester supply for endo lab — best value per tooth",
      longDesc:
        "Three standard sets in one pack — enough for a full semester of endodontics practice. Best per-tooth value for students who train weekly in lab.",
      features: [
        "24 practice teeth total",
        "14% savings vs 3 separate sets",
        "Mixed canal anatomy",
        "Semester-ready supply",
      ],
      specifications: {
        Quantity: "24 teeth (3× sets)",
        Savings: "14% vs individual sets",
        Canal: "Mixed anatomy",
        Pack: "Bulk lab box",
      },
      featured: 85,
      date: "2025-09-12",
    },
    {
      id: "et-003",
      sku: "MF-ET-003",
      name: "Endo Teeth — Curved Canal",
      category: "endo-teeth",
      categoryLabel: "Endodontics",
      price: 420,
      compareAt: null,
      badge: null,
      inStock: true,
      image: "images/endo-teeth-red-roots.jpg",
      gallery: [
        "images/endo-teeth-red-roots.jpg",
        "images/mandible-cast.jpg",
      ],
      desc: "Advanced curvature for Year 4+ endodontic technique",
      longDesc:
        "Designed for advanced endodontics — pronounced canal curvature for negotiation and shaping practice before clinic cases.",
      features: [
        "8 teeth with curved canals",
        "Advanced difficulty level",
        "Year 4+ recommended",
        "Faculty-aligned anatomy",
      ],
      specifications: {
        Quantity: "8 teeth",
        Canal: "Moderate–severe curvature",
        Level: "Advanced",
        Material: "Resin",
      },
      featured: 70,
      date: "2025-07-08",
    },
    {
      id: "dc-001",
      sku: "MF-DC-001",
      name: "Dental Cast — Maxillary Arch",
      category: "dental-casts",
      categoryLabel: "Prosthodontics",
      price: 520,
      compareAt: null,
      badge: "Popular",
      inStock: true,
      image: "images/dental-casts-kit.jpg",
      gallery: [
        "images/dental-casts-kit.jpg",
        "images/mandible-cast.jpg",
        "images/typodont-flatlay.jpg",
      ],
      desc: "Anatomical upper arch for crown prep and wax-up study",
      longDesc:
        "Clear anatomical landmarks for crown preparation, wax-up, and occlusion study. Essential for prosthodontics and restorative modules.",
      features: [
        "Full maxillary arch model",
        "Clear occlusal anatomy",
        "Ideal for crown prep practice",
        "Durable stone-like resin",
        "Bench-stable base",
      ],
      specifications: {
        Arch: "Maxillary (upper)",
        Teeth: "Full arch",
        Material: "High-density resin",
        Use: "Crown prep, wax-up, study",
        Base: "Flat mounting base",
      },
      featured: 88,
      date: "2025-08-22",
    },
    {
      id: "dc-002",
      sku: "MF-DC-002",
      name: "Dental Cast — Mandibular Arch",
      category: "dental-casts",
      categoryLabel: "Prosthodontics",
      price: 520,
      compareAt: null,
      badge: null,
      inStock: true,
      image: "images/mandible-cast.jpg",
      gallery: [
        "images/mandible-cast.jpg",
        "images/dental-casts-kit.jpg",
      ],
      desc: "Lower arch model with clear occlusal anatomy",
      longDesc:
        "Matched quality to our maxillary cast — complete mandibular arch for articulation exercises and lower crown preparations.",
      features: [
        "Full mandibular arch",
        "Matched to MF-DC-001",
        "Articulation-ready",
        "Prosthodontics lab standard",
      ],
      specifications: {
        Arch: "Mandibular (lower)",
        Teeth: "Full arch",
        Material: "High-density resin",
        Pairing: "Pairs with MF-DC-001",
      },
      featured: 82,
      date: "2025-08-22",
    },
    {
      id: "dc-003",
      sku: "MF-DC-003",
      name: "Dental Cast Pair (Upper + Lower)",
      category: "dental-casts",
      categoryLabel: "Prosthodontics",
      price: 950,
      compareAt: 1040,
      badge: "Bundle",
      inStock: true,
      image: "images/typodont-flatlay.jpg",
      gallery: [
        "images/typodont-flatlay.jpg",
        "images/dental-casts-kit.jpg",
        "images/typodont-open.jpg",
      ],
      desc: "Matched arch set for articulation and full-mouth prep",
      longDesc:
        "Save vs buying arches separately. Matched occlusion for full-mouth prosthodontics, articulation, and comprehensive crown-and-bridge practice.",
      features: [
        "Upper + lower arch included",
        "Matched occlusion",
        "Bundle savings",
        "Full-mouth prep ready",
      ],
      specifications: {
        Includes: "MF-DC-001 + MF-DC-002",
        Savings: "EGP 90 vs separate",
        Arches: "Maxillary + mandibular",
        Pack: "Dual arch box",
      },
      featured: 92,
      date: "2025-09-05",
    },
    {
      id: "dk-001",
      sku: "MF-DK-001",
      name: "Year 2 Lab Starter Kit",
      category: "dental-kits",
      categoryLabel: "Kit",
      price: 1850,
      compareAt: 2100,
      badge: "Bestseller",
      inStock: true,
      image: "images/dental-casts-kit.jpg",
      gallery: [
        "images/dental-casts-kit.jpg",
        "images/typodont-open.jpg",
        "images/endo-teeth-bulk.jpg",
      ],
      desc: "Casts, model teeth & consumables curated for Year 2 modules",
      longDesc:
        "Stop chasing ten separate orders. Everything on the typical Year 2 lab list in one curated kit — casts, practice teeth, and essential consumables.",
      features: [
        "Curated for Year 2 Egyptian curricula",
        "Casts + practice teeth included",
        "Checklist inside the box",
        "Save vs buying separately",
        "One delivery, one invoice",
      ],
      specifications: {
        Target: "Year 2 students",
        Includes: "Casts, teeth, consumables",
        Savings: "~12% vs separate",
        Delivery: "Single shipment",
      },
      featured: 98,
      date: "2025-10-15",
    },
    {
      id: "dk-002",
      sku: "MF-DK-002",
      name: "Endodontics Practice Kit",
      category: "dental-kits",
      categoryLabel: "Kit",
      price: 1200,
      compareAt: null,
      badge: "Lab essential",
      inStock: true,
      image: "images/endo-teeth-bulk.jpg",
      gallery: [
        "images/endo-teeth-bulk.jpg",
        "images/endo-teeth-red-roots.jpg",
      ],
      desc: "Endo teeth sets, access materials & guide for one semester",
      longDesc:
        "Complete endodontics lab companion — multiple endo teeth sets plus a printed guide aligned with common faculty requirements.",
      features: [
        "2× Endo Teeth sets included",
        "Printed lab checklist",
        "Semester-ready",
        "WhatsApp setup support",
      ],
      specifications: {
        Target: "Year 3–4 endo module",
        Includes: "2 endo sets + guide",
        Teeth: "16 total",
      },
      featured: 94,
      date: "2025-09-28",
    },
    {
      id: "dk-003",
      sku: "MF-DK-003",
      name: "Prosthodontics Essentials Kit",
      category: "dental-kits",
      categoryLabel: "Kit",
      price: 1450,
      compareAt: 1620,
      badge: "Save 10%",
      inStock: true,
      image: "images/dental-casts-kit.jpg",
      gallery: [
        "images/dental-casts-kit.jpg",
        "images/mandible-cast.jpg",
      ],
      desc: "Upper & lower casts plus prep accessories for prostho lab",
      longDesc:
        "Everything for prosthodontics practical sessions — matched cast pair plus prep accessories in one premium kit box.",
      features: [
        "Dental cast pair included",
        "Prep accessories bundle",
        "10% bundle savings",
        "Prostho module aligned",
      ],
      specifications: {
        Target: "Prosthodontics students",
        Includes: "Cast pair + accessories",
        Savings: "10%",
      },
      featured: 91,
      date: "2025-08-30",
    },
    {
      id: "dk-004",
      sku: "MF-DK-004",
      name: "Complete Simulation Kit",
      category: "dental-kits",
      categoryLabel: "Kit",
      price: 4200,
      compareAt: 4680,
      badge: "Premium",
      inStock: true,
      image: "images/dummy-head-open.jpg",
      gallery: [
        "images/dummy-head-open.jpg",
        "images/typodont-1.jpg",
        "images/dental-casts-kit.jpg",
        "images/endo-teeth-red-roots.jpg",
      ],
      desc: "Dummy head, casts, endo teeth & accessories — full lab setup",
      longDesc:
        "The ultimate MedFactory bundle — dummy head, cast pair, endo teeth, and typodont accessories for students building a complete simulation training setup.",
      features: [
        "Dummy head with articulator",
        "Full cast pair + endo sets",
        "Premium lab accessories",
        "Maximum bundle savings",
        "Priority WhatsApp support",
      ],
      specifications: {
        Target: "Year 4+ / comprehensive training",
        Includes: "Head, casts, endo, accessories",
        Savings: "~10% vs separate",
        Tier: "Premium bundle",
      },
      featured: 99,
      date: "2025-10-20",
    },
  ];

  function getById(id) {
    return PRODUCTS.find((p) => p.id === id) || null;
  }

  function getRelated(product, limit = 4) {
    return PRODUCTS.filter(
      (p) => p.id !== product.id && p.category === product.category
    )
      .sort((a, b) => b.featured - a.featured)
      .slice(0, limit);
  }

  return {
    CATEGORIES,
    PRODUCTS,
    getById,
    getRelated,
  };
})();
